# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daskFunctions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61skFunctions.proto\"\x19\n\x08NameFile\x12\r\n\x05value\x18\x01 \x01(\t\"\x17\n\x06Return\x12\r\n\x05value\x18\x01 \x01(\t20\n\rDaskFunctions\x12\x1f\n\x07ReadCSV\x12\t.NameFile\x1a\x07.Return\"\x00\x62\x06proto3')



_NAMEFILE = DESCRIPTOR.message_types_by_name['NameFile']
_RETURN = DESCRIPTOR.message_types_by_name['Return']
NameFile = _reflection.GeneratedProtocolMessageType('NameFile', (_message.Message,), {
  'DESCRIPTOR' : _NAMEFILE,
  '__module__' : 'daskFunctions_pb2'
  # @@protoc_insertion_point(class_scope:NameFile)
  })
_sym_db.RegisterMessage(NameFile)

Return = _reflection.GeneratedProtocolMessageType('Return', (_message.Message,), {
  'DESCRIPTOR' : _RETURN,
  '__module__' : 'daskFunctions_pb2'
  # @@protoc_insertion_point(class_scope:Return)
  })
_sym_db.RegisterMessage(Return)

_DASKFUNCTIONS = DESCRIPTOR.services_by_name['DaskFunctions']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAMEFILE._serialized_start=23
  _NAMEFILE._serialized_end=48
  _RETURN._serialized_start=50
  _RETURN._serialized_end=73
  _DASKFUNCTIONS._serialized_start=75
  _DASKFUNCTIONS._serialized_end=123
# @@protoc_insertion_point(module_scope)
